### ISSUE TITLE
False positive validation error for Index MetaDB

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/providers-dashboard#1]
I think the [following validation error](https://www.optimade.org/providers-dashboard/providers/cod.html) complaining about [the COD Index MetaDB](https://www.optimade.org/providers-dashboard/providers/cod.html) is a false positive:
```
Error while validating the Index MetaDB:
Traceback (most recent call last):
File "make_pages.py", line 73, in get_index_metadb_data
info_response = IndexInfoResponse(**json_response)
File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for IndexInfoResponse
data -> relationships -> default -> data -> type
unexpected value; permitted: 'child' (type=value_error.const; given=links; permitted=['child'])
meta -> time_stamp
field required (type=value_error.missing)
meta -> data_returned
field required (type=value_error.missing)
meta -> provider
field required (type=value_error.missing)
```
According to the [OPTIMADE specification](https://www.optimade.org/providers-dashboard/providers/cod.html), value of `data/relationships/default/data/type` can only be `links`, but the validator insists on `child`.

**Comment by CasperWA** [comment]
Agreed. This is an issue of the OPTIMADE Python tools validator.
I believe we already fixed the data type issue, while we have not yet updated the newly changed `meta` property tiers of requirement.

Feel free to contribute to [`optimade-python-tools`](https://github.com/Materials-Consortia/optimade-python-tools).

**Comment by merkys** [comment]
Thanks for the prompt response!

**Comment by CasperWA** [comment]
> Thanks for the prompt response!

Sure :) In the end, this issue is not specific to the COD index meta-database, but rather for all index meta-databases at the moment. Indeed, the `meta` validation is an issue for any and all OPTIMADE implementation validation.
So again, any contributions to the validator are welcome :)
