### ISSUE TITLE
The "Available providers" value does not match its description

### ISSUE THREAD

**Issue by vaitkus** [Materials-Consortia/providers-dashboard#159]
The tooltip for the "Available providers" label describes it as "Providers that specify an OPTIMADE base URL", however, the associated value seems to always match the number of providers with ids (see the "with_base_url" field) :

https://github.com/Materials-Consortia/providers-dashboard/blob/f536de9c71cead2288445cafb3a7e712e637c35d/make_ghpages/make_pages.py#L403-L416

Currently, there is at least one provider that does not provide a base URL (pcod), however, this fact is not reflected in the dashboard.

**Comment by ml-evs** [comment]
Closed by a48344d

**Comment by ml-evs** [comment]
Oh yeah... I'll fix it differently then ;)

**Comment by vaitkus** [comment]
Seem to be fixed with https://github.com/Materials-Consortia/providers-dashboard/commit/b0d408b03f7a104f9b4525c22ed04a710ea66b9d, thanks!
