### ISSUE TITLE
[nmd] Double scheme in `meta -> provider -> homepage`

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/providers-dashboard#3]
The nomad index meta-database has a double scheme value for `provider -> homepage`.

As I don't know wherelse to put this issue (since I can't create one in the implementation's repository), I'll create it here, and it can be closed by NOMAD implementers when the issue has been resolved :)

Note, this was found through this dashboard and the error shown when hovering over the badges under the NOMAD implementation site for checking the `/links` and `/info` endpoints.

Here is a replication of the `provider` under the top-level `meta` field.

```json
"provider": {
      "name": "novel materials discovery (NOMAD)",
      "description": "novel materials discovery (NOMAD)",
      "prefix": "nomad",
      "homepage": "https://https://nomad-lab.eu",
      "index_base_url": "https://nomad-lab.eu/prod/rae/optimade/index"
}
```

**Comment by markus1978** [comment]
Thanks for the report. Yes its a pain that MaxPlancks gitlab does not allow externals to create issues. I fixed this and there is also a pr to the providers project with our new URLs.

**Comment by CasperWA** [comment]
> Thanks for the report. Yes its a pain that MaxPlancks gitlab does not allow externals to create issues. I fixed this and there is also a pr to the providers project with our new URLs.

Cheers. I'll consider this issue resolved then.
I found another thing, but I have reported that in my review over at the `providers` repository. It doesn't alter the approval of said PR though :)
