### ISSUE TITLE
Dashboard keeps timing out

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/providers-dashboard#80]
The dashboard build has been timing out after 2 hours recently. I think one implementation is being very slow to return data, but fast enough to respond that it is not hitting the internal validator timeout. I will probably add a per-database timeout of ~20 minutes.

**Comment by rartino** [comment]
Might be my fault, we've had some downtime the last couple of days due to an upgrade that went wrong... Most of the time the computer have been completely down and non-responsive - in case that helps to try to understand what timeout is missing.

**Comment by ml-evs** [comment]
Hi @rartino, thanks for the tip but according to the logs I think you were fine :) I've added an additional couple of timeouts to the validator in the python-tools package, just need to wait for the next release

**Comment by ml-evs** [comment]
This seems to have been fixed by #81.
